[
  {
    name: "Dr. Asha Verma",
    date: "2025-05-19",
    staffId: "DOC1001",
    department: "Cardiology",
    role: "Doctor",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Dr. Kunal Das",
    date: "2025-05-19",
    staffId: "DOC1002",
    department: "Cardiology",
    role: "Doctor",
    shift: "Night",
    status: "Absent",
  },
  {
    name: "Dr. Reena Roy",
    date: "2025-05-19",
    staffId: "DOC1003",
    department: "Cardiology",
    role: "Doctor",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Priya Sharma",
    date: "2025-05-19",
    staffId: "NUR2001",
    department: "Cardiology",
    role: "Nurse",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nurse Vikram Jha",
    date: "2025-05-19",
    staffId: "NUR2002",
    department: "Cardiology",
    role: "Nurse",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Meena Rai",
    date: "2025-05-19",
    staffId: "NUR2003",
    department: "Cardiology",
    role: "Nurse",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Ravi Menon",
    date: "2025-05-19",
    staffId: "TECH3001",
    department: "Cardiology",
    role: "Technician",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Ankit Saxena",
    date: "2025-05-19",
    staffId: "TECH3002",
    department: "Cardiology",
    role: "Technician",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Pallavi Joshi",
    date: "2025-05-19",
    staffId: "TECH3003",
    department: "Cardiology",
    role: "Technician",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Tanvi",
    date: "2025-05-19",
    staffId: "ADM5001",
    department: "Cardiology",
    role: "Admin Assistant",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Saurabh Mishra",
    date: "2025-05-19",
    staffId: "ADM5002",
    department: "Cardiology",
    role: "Admin Assistant",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nikita Jain",
    date: "2025-05-19",
    staffId: "ADM5003",
    department: "Cardiology",
    role: "Admin Assistant",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Dr. Neha Sood",
    date: "2025-05-19",
    staffId: "DOC1011",
    department: "Emergency",
    role: "Doctor",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Dr. Abhay Kumar",
    date: "2025-05-19",
    staffId: "DOC1012",
    department: "Emergency",
    role: "Doctor",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Dr. Faria Sheikh",
    date: "2025-05-19",
    staffId: "DOC1013",
    department: "Emergency",
    role: "Doctor",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Nurse Sunita Rao",
    date: "2025-05-19",
    staffId: "NUR2011",
    department: "Emergency",
    role: "Nurse",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nurse Rajiv Iyer",
    date: "2025-05-19",
    staffId: "NUR2012",
    department: "Emergency",
    role: "Nurse",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Beena Joseph",
    date: "2025-05-19",
    staffId: "NUR2013",
    department: "Emergency",
    role: "Nurse",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Deepak Yadav",
    date: "2025-05-19",
    staffId: "TECH3011",
    department: "Emergency",
    role: "Technician",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nikhil Thakur",
    date: "2025-05-19",
    staffId: "TECH3012",
    department: "Emergency",
    role: "Technician",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Priti Mehta",
    date: "2025-05-19",
    staffId: "TECH3013",
    department: "Emergency",
    role: "Technician",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Steve",
    date: "2025-05-19",
    staffId: "ADM5011",
    department: "Emergency",
    role: "Admin Assistant",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Sameer Khan",
    date: "2025-05-19",
    staffId: "ADM5012",
    department: "Emergency",
    role: "Admin Assistant",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Lina D'Souza",
    date: "2025-05-19",
    staffId: "ADM5013",
    department: "Emergency",
    role: "Admin Assistant",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Dr. Rohit Nair",
    date: "2025-05-19",
    staffId: "DOC1021",
    department: "ICU",
    role: "Doctor",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Dr. Sneha Tiwari",
    date: "2025-05-19",
    staffId: "DOC1022",
    department: "ICU",
    role: "Doctor",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Dr. Varun Seth",
    date: "2025-05-19",
    staffId: "DOC1023",
    department: "ICU",
    role: "Doctor",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Nurse Anjali Kapoor",
    date: "2025-05-19",
    staffId: "NUR2021",
    department: "ICU",
    role: "Nurse",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nurse Rohit Roy",
    date: "2025-05-19",
    staffId: "NUR2022",
    department: "ICU",
    role: "Nurse",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Minal Jain",
    date: "2025-05-19",
    staffId: "NUR2023",
    department: "ICU",
    role: "Nurse",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Pooja Mishra",
    date: "2025-05-19",
    staffId: "TECH3021",
    department: "ICU",
    role: "Technician",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Sameer Ahuja",
    date: "2025-05-19",
    staffId: "TECH3022",
    department: "ICU",
    role: "Technician",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Anuja Vernekar",
    date: "2025-05-19",
    staffId: "TECH3023",
    department: "ICU",
    role: "Technician",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Robo",
    date: "2025-05-19",
    staffId: "ADM5021",
    department: "ICU",
    role: "Admin Assistant",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Tushar Sharma",
    date: "2025-05-19",
    staffId: "ADM5022",
    department: "ICU",
    role: "Admin Assistant",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nancy Gupta",
    date: "2025-05-19",
    staffId: "ADM5023",
    department: "ICU",
    role: "Admin Assistant",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Dr. Rakesh Mehra",
    date: "2025-05-19",
    staffId: "DOC1031",
    department: "Radiology",
    role: "Doctor",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Dr. Shruti Jain",
    date: "2025-05-19",
    staffId: "DOC1032",
    department: "Radiology",
    role: "Doctor",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Dr. Nilesh Patil",
    date: "2025-05-19",
    staffId: "DOC1033",
    department: "Radiology",
    role: "Doctor",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Nurse Kavita Desai",
    date: "2025-05-19",
    staffId: "NUR2031",
    department: "Radiology",
    role: "Nurse",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nurse Aman Singh",
    date: "2025-05-19",
    staffId: "NUR2032",
    department: "Radiology",
    role: "Nurse",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Tina Paul",
    date: "2025-05-19",
    staffId: "NUR2033",
    department: "Radiology",
    role: "Nurse",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Amit Sinha",
    date: "2025-05-19",
    staffId: "TECH3031",
    department: "Radiology",
    role: "Technician",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Kritika Singh",
    date: "2025-05-19",
    staffId: "TECH3032",
    department: "Radiology",
    role: "Technician",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Vikrant Chauhan",
    date: "2025-05-19",
    staffId: "TECH3033",
    department: "Radiology",
    role: "Technician",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Kumar",
    date: "2025-05-19",
    staffId: "ADM5031",
    department: "Radiology",
    role: "Admin Assistant",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Reshma Qureshi",
    date: "2025-05-19",
    staffId: "ADM5032",
    department: "Radiology",
    role: "Admin Assistant",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "George Mathew",
    date: "2025-05-19",
    staffId: "ADM5033",
    department: "Radiology",
    role: "Admin Assistant",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Dr. Sangeeta Rao",
    date: "2025-05-19",
    staffId: "DOC1041",
    department: "General Medicine",
    role: "Doctor",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Dr. Mohit Rana",
    date: "2025-05-19",
    staffId: "DOC1042",
    department: "General Medicine",
    role: "Doctor",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Dr. Alia Fernandes",
    date: "2025-05-19",
    staffId: "DOC1043",
    department: "General Medicine",
    role: "Doctor",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Nurse Alok Verma",
    date: "2025-05-19",
    staffId: "NUR2041",
    department: "General Medicine",
    role: "Nurse",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Nurse Shalini Bhatt",
    date: "2025-05-19",
    staffId: "NUR2042",
    department: "General Medicine",
    role: "Nurse",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Nurse Darshan Bhatia",
    date: "2025-05-19",
    staffId: "NUR2043",
    department: "General Medicine",
    role: "Nurse",
    shift: "Night",
    status: "Present",
  },
  {
    name: "Sneha Bansal",
    date: "2025-05-19",
    staffId: "TECH3041",
    department: "General Medicine",
    role: "Technician",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Ujjwal Yadav",
    date: "2025-05-19",
    staffId: "TECH3042",
    department: "General Medicine",
    role: "Technician",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Disha Thakkar",
    date: "2025-05-19",
    staffId: "TECH3043",
    department: "General Medicine",
    role: "Technician",
    shift: "Night",
    status: "Present",
  },
  {
    name: "John",
    date: "2025-05-19",
    staffId: "ADM5041",
    department: "General Medicine",
    role: "Admin Assistant",
    shift: "Morning",
    status: "Present",
  },
  {
    name: "Aarav Singh",
    date: "2025-05-19",
    staffId: "ADM5042",
    department: "General Medicine",
    role: "Admin Assistant",
    shift: "Afternoon",
    status: "Present",
  },
  {
    name: "Laxmi Menon",
    date: "2025-05-19",
    staffId: "ADM5043",
    department: "General Medicine",
    role: "Admin Assistant",
    shift: "Night",
    status: "Present",
  },
];
